version: 2
jobs:
    test:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1.2-dependencies-{{ checksum "package.json" }}
                      - v1.2-dependencies-
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: npm run test

    release:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1.2-dependencies-{{ checksum "package.json" }}
                      - v1.2-dependencies-
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: npm run build
            - run: npx semantic-release@beta

workflows:
    version: 2
    test_and_release:
        jobs:
            - test
            - approve_release:
                  type: approval
                  requires:
                      - test
            - release:
                  requires:
                      - approve_release
                  filters:
                      branches:
                          only:
                              - master
                              - /^([0-9]+)(\.([0-9]+|x))?\.x$/
                              - beta
